"""Post - added date_updated

Revision ID: b83132d1751f
Revises: f03ee3cbc839
Create Date: 2021-08-29 20:34:57.601578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83132d1751f'
down_revision = 'f03ee3cbc839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date_update')
    # ### end Alembic commands ###
