"""Post - added date_updated

Revision ID: c319f0dc2edf
Revises: b83132d1751f
Create Date: 2021-08-29 20:36:34.762743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c319f0dc2edf'
down_revision = 'b83132d1751f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.drop_column('post', 'date_update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_update', sa.DATETIME(), nullable=True))
    op.drop_column('post', 'date_updated')
    # ### end Alembic commands ###
